

export const INCREMENT_COUNTER = "INCREMENT_COUNTER"

export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const ADD_COMMENT = "ADD_COMMENT"
export const GET_COMMENT = "GET_COMMENT"
export const DELETE_COMMENT = "DELETE_COMMENT"
export const LODING_COMMENT = "LODING_COMMENT"
export const ERROR_COMMENT = "ERROR_COMMENT"